<!-- Main content -->
<section class="content ">

    <div class="container">
        <div class="container-fluid">
            <h3 class="text-dark mb-4">Lead Programmer - Proyek</h3>
            <div class="card shadow" style="border-bottom-right-radius: 15px;border-top-right-radius: 15px;border-top-left-radius: 15px;border-bottom-left-radius: 15px;">
                <div class="card-header py-3" style="border-top-left-radius: 15px;border-top-right-radius: 15px;">
                    <div class="row">
                        <div class="col-md-12 col-lg-12 ">
                            <p class="text-primary m-0 fw-bold">Harap lengkapi input yang diperlukan, sebelum Anda mengklik tombol kirim</p>
                        </div>

                    </div>
                </div>
                <div class="card-body">
                    <form method="post" action="/operator/kirim">
                        <div class="col">
                            <div class="d-none">
                                <div class="mb-3"><label class="form-label"><strong>ID</strong><br /></label><input id="id" name="id" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id'] ?>" /></div>
                            </div>
                            <div class="mb-3"><label class="form-label"><strong>Proyek</strong><br /></label><input id="pelapor" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['proyek'] ?>" disabled /></div>
                            <div class="mb-3">
                                <label><strong>Pilih Lead Programmer</strong></label>
                                <select class="w-100" data-placeholder="Pilih Petugas" name="leader_programmer">
                                    <?php
                                    foreach ($this->data['list_programmer'] as $data) {
                                        echo '<option value="' . $data['id'] . '">' . $data['nama'] . '</option>';
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="d-flex justify-content-end">
                            <button class="btn text-white m-2" style="background-color: #34abbb;"><i class="fa-regular fa-square-check"></i> Kirim</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</section>

<!-- /.content -->