<!-- Main content -->
<section class="content">
    <div class="container">
        <div class="container-fluid">
            <h3 class="text-dark mb-4">Proyek Lead Programmer</h3>
            <div class="card shadow" style="border-bottom-right-radius: 15px;border-top-right-radius: 15px;border-top-left-radius: 15px;border-bottom-left-radius: 15px;">
                <div class="card-header py-3" style="border-top-left-radius: 15px;border-top-right-radius: 15px;">
                    <div class="row">
                        <div class="col-md-6 col-lg-6 ">
                            <p class="text-primary m-0 fw-bold">Daftar Proyek Lead Programmer</p>
                        </div>

                    </div>
                </div>
                <div class="card-body">

                    <div class="table-responsive table mt-2" role="grid" aria-describedby="dataTable_info" style="background: var(--bs-table-bg);border-radius: 10px;">
                        <table class="table table-striped" id="project">
                            <thead style="background: rgba(208,204,204,0.76);">
                                <tr>
                                    <th class="text-center">Tanggal</th>
                                    <th class="text-center">Jam</th>
                                    <th class="text-center">Leader</th>
                                    <th>Project</th>
                                    <th class="text-center">Tindakan</th>
                                </tr>
                            </thead>
                            <tbody style="background: rgba(231,231,231,0.64);" id="auto">

                                <?php
                                if ($this->data != null) {
                                    foreach ($this->data as $data) {
                                        echo "<tr>";

                                        echo "<td align='center'>" . $data['tanggal'] . "</td>";
                                        echo "<td align='center'>" . $data['jam'] . "</td>";
                                        echo "<td>" . $data['leader'] . "</td>";
                                        echo "<td>" . $data['project'] . "</td>";

                                        echo "<td align='center' background: rgb(223,78,87);>";
                                        echo "<a class='btn btn-primary' type='button' style='margin: 13px;background: rgb(53,168,184);' href='/operator/project-edit/id_tiket/" . $data['id_tiket'] . "'>DETAIL</a>";
                                        echo "</td>";

                                        echo "</tr>";
                                    }
                                }
                                ?>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- /.content -->