<!-- Main content -->
<section class="content ">

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="exampleModalLabel">Keterangan Revisi</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" action="/operator/revisi">
                        <div class="d-none">
                            <div class="mb-3"><label class="form-label"><strong>ID</strong><br /></label><input id="id" name="id" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id'] ?>" /></div>
                        </div>
                        <label class="form-label fw-normal">Keterangan</label>
                        <textarea class="form-control" id="alamat" rows="4" placeholder="Keterangan Revisi" name="keterangan"></textarea>
                        <div class="d-flex align-items-end justify-content-end">
                            <button class="btn text-white m-2" style="background-color: #34abbb;"><i class="fa-regular fa-square-check"></i> Kirim</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button> -->
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="selesai" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="exampleModalLabel">Penyelesaian</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" action="/programmer/selesai">
                        <div class="d-none">
                            <div class="mb-3"><label class="form-label"><strong>ID TIKET</strong><br /></label><input id="id" name="id_tiket" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tiket'] ?>" /></div>
                            <!-- <div class="mb-3"><label class="form-label"><strong>ID TAHAPAN</strong><br /></label><input id="id" name="id_tahapan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tahapan'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TODO LIST</strong><br /></label><input id="id_todo" name="id_todo_list" class="form-control" type="text" style="border-radius: 10px;" /></div> -->
                        </div>
                        <div class="text-center mb-2">
                            Apakah anda yakin untuk diselesaikan ?
                        </div>
                        <div class="d-flex align-items-end justify-content-center">
                            <a class="btn text-white m-2" style="background-color: #34abbb;" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i> Batal</a>
                            <button class="btn text-white m-2" style="background-color: red;"><i class="fa-regular fa-square-check"></i> Selesai</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="lanjut" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="exampleModalLabel">Pelanjutan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" action="/programmer/lanjutkan">
                        <div class="d-none">
                            <div class="mb-3"><label class="form-label"><strong>ID TIKET</strong><br /></label><input id="id" name="id_tiket" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tiket'] ?>" /></div>
                            <!-- <div class="mb-3"><label class="form-label"><strong>ID TAHAPAN</strong><br /></label><input id="id" name="id_tahapan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tahapan'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TODO LIST</strong><br /></label><input id="id_todo" name="id_todo_list" class="form-control" type="text" style="border-radius: 10px;" /></div> -->
                        </div>
                        <div class="text-center mb-2">
                            Apakah anda yakin untuk dilanjutkan pada tahun depan ?
                        </div>
                        <div class="d-flex align-items-end justify-content-center">
                            <a class="btn text-white m-2" style="background-color: #34abbb;" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i> Batal</a>
                            <button class="btn text-white m-2" style="background-color: orange;"><i class="fa-regular fa-square-check"></i> Lanjut</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container-fluid">
            <h3 class="text-dark mb-4">Detail Permintaan</h3>
            <div class="card shadow" style="border-bottom-right-radius: 15px;border-top-right-radius: 15px;border-top-left-radius: 15px;border-bottom-left-radius: 15px;">
                <div class="card-header py-3" style="border-top-left-radius: 15px;border-top-right-radius: 15px;">
                    <div class="row">
                        <div class="col-md-6 col-lg-6 ">
                            <p class="text-primary m-0 fw-bold">Detail Permintaan Aplikasi (<?= $this->data['peran'] ?>)</p>
                        </div>

                    </div>
                </div>
                <div class="card-body">

                        <div class="col">

                            <div class="d-none">
                                <div class="mb-3"><label class="form-label"><strong>ID</strong><br /></label><input id="id" name="id" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id'] ?>" /></div>
                            </div>
                            <div class="mb-3"><label class="form-label"><strong>Pelapor</strong><br /></label><input id="pelapor" name="pelapor" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['pelapor'] ?>" disabled /></div>
                            <div class="mb-3"><label class="form-label"><strong>Permasalahan</strong><br /></label><input id="permasalahan" name="permasalahan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['permasalahan'] ?>" disabled /></div>
                            <div class="mb-3"><label class="form-label"><strong>Email</strong><br /></label><input id="email" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['email'] ?>" disabled /></div>
                        </div>
                        <div class="col">
                            <div class="mb-3"><label class="form-label"><strong>Nomor Telepon</strong></label><input id="no_telepon" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['no_telepon'] ?>" disabled /></div>
                            <div class="mb-3"><label class="form-label"><strong>Dokumen Lampiran</strong><br /></label><br>
                                <?php
                                if ($this->data['dokumen_lampiran']) {
                                    foreach ($this->data['dokumen_lampiran'] as $i) {
                                        echo '<div><a target="_blank" href="' . "/storage/index/dokumen-lampiran/{$i['doc_name']}/ext/{$i['ext']}" . '"><i class="fa-regular fa-file fs-4 ms-2"></i></a></div>';
                                    }
                                }
                                ?>
                            </div>
                            <div class="mb-3"><label class="form-label"><strong>Deskripsi Masalah</strong><br /></label><textarea id="keterangan" class="form-control" rows="5" name="signature" style="border-radius: 15px;" disabled><?= $this->data['deskripsi'] ?></textarea></div>
                            <div class="mb-3"><label class="form-label"><strong>Nama Aplikasi</strong></label><input id="no_telepon" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['aplikasi'] ?>" disabled /></div>
                            <? if ($this->data['aplikasi'] == null && $this->data['peran'] == 'leader' && $this->data['reference_to'] == null) { ?>
                                <form method="post" class="needs-validation" action="/programmer/konfirmasi" novalidate>
                                    <div class="mb-3"><input id="id" name="id_tiket" class="form-control" type="hidden" style="border-radius: 10px;" value="<?= $this->data['id_tiket'] ?>"/></div>
                                    <label for="jenis" class="form-label"><strong>Pilih Aplikasi</strong><br /></label>
                                    <select class="form-select" name="id_aplikasi" id="jenis" required>
                                        <?php
                                        echo '<option disabled selected value> -- Tentukan Pilihan -- </option>';
                                        foreach ($this->data['list_aplikasi'] as $data) {
                                            echo '<option value="' . $data['id'] . '">' . $data['aplikasi'] . '</option>';
                                        }
                                        ?>
                                    </select>
                                    <div class="invalid-feedback">
                                        Tolong pilih Aplikasi!
                                    </div>
                                    <div class="valid-feedback">
                                        Baik!
                                    </div>
                                    <button class="btn text-white mt-2 bg-success"><i class="fa-regular fa-square-check"></i> Konfirmasi</button>
                                </form>
                                <div class="text-danger">*Harap Tentukan Aplikasi Terlebih Dahulu</div>
                            <? } ?>
                            <div class="row">
                                <div class="mb-3 col-md-6">
                                    <? if ($this->data['reference_by'] != null) { ?>
                                        <label class="form-label"><strong>Lanjutan Pada</strong> <a href="/programmer/permintaan/detail/<?= $this->data['reference_by'] ?>">Tiket</a> </label>
                                    <? } ?>
                                </div>
                                <div class="mb-3 col-md-6 d-flex justify-content-end">
                                    <? if ($this->data['reference_to'] != null) { ?>
                                        <label class="form-label"><strong>Dilanjutkan Pada</strong> <a href="/programmer/permintaan/detail/<?= $this->data['reference_to'] ?>">Tiket</a> </label>
                                    <? } ?>
                                </div>
                            </div>
                        </div>
                        <div class="d-flex align-items-end justify-content-end">
                            <a class='btn text-white m-2' type='button' style='background: #00838f;' href='/programmer/permintaan'><i class="fa-solid fa-delete-left"></i> Batal</a>
                            <? if ($this->data['aplikasi']) { ?>
                                <a class='btn text-white m-2 bg-primary' type='button' href='/programmer/log/id/<?= $this->data['id_tiket'] ?>'><i class="fa-solid fa-clipboard-list"></i> Log</a>
                                <? if ($this->data['peran'] == 'leader') { ?>
                                    <? if (!$this->data['reference_to'] && $this->data['id_status_tiket'] != 6) { ?>
                                        <a class='btn text-white m-2 bg-warning' style='color:white !important;' type='button' data-bs-toggle="modal" data-bs-target="#lanjut"><i class="fa-solid fa-diagram-next"></i> Lanjutkan</a>
                                        <? if ($this->data['id_status_tiket'] != 6) { ?>
                                            <a class='btn text-white m-2' type='button' style='background: #ff5050;' data-bs-toggle="modal" data-bs-target="#selesai"><i class="fa-solid fa-flag-checkered"></i> Selesai</a>
                                        <? } ?>
                                        <a class='btn text-white m-2' type='button' style='background: #34abbb;' href='/programmer/tim/id_tiket/<?= $this->data['id_tiket']; ?>'><i class="fa-regular fa-square-check"></i> Kirim</a>
                            <? }
                                }
                            } ?>
                        </div>

                </div>
            </div>
        </div>
    </div>

</section>

<!-- /.content -->