<!-- Main content -->
<section class="content">
    <!-- Modal -->
    <div class="modal fade" id="sukses" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                </div>
                <div class="modal-body">

                    <i class="fa-solid fa-circle-check w-100 text-center" style="font-size: 50px;color:#28d094"></i>
                    <label class="form-label w-100 fw-bold fs-2 text-center mb-3">PESAN SUKSES</label>
                    <br>
                    <label class="w-100 form-label fw-normal text-center mb-3">Sukses Tambah Tim Programmer</label>
                </div>
                <div class="modal-footer">

                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container-fluid">
            <h3 class="text-dark mb-4">Daftar Permintaan</h3>
            <div class="card shadow" style="border-bottom-right-radius: 15px;border-top-right-radius: 15px;border-top-left-radius: 15px;border-bottom-left-radius: 15px;">
                <div class="card-header py-3" style="border-top-left-radius: 15px;border-top-right-radius: 15px;">
                    <div class="row">
                        <div class="col-md-6 col-lg-6 ">
                            <p class="text-primary m-0 fw-bold">List Permintaan Aplikasi</p>
                        </div>
                    </div>
                </div>
                <div class="card-body">

                    <div class="table-responsive table mt-2" role="grid" aria-describedby="dataTable_info" style="background: var(--bs-table-bg);border-radius: 10px;">
                        <table class="table table-striped" id="programmer">
                            <thead style="background: rgba(208,204,204,0.76);">
                                <tr>
                                    <th width="100" class="text-center">Tanggal</th>
                                    <th class="text-center">Jam</th>
                                    <th class="text-center">Kode Tiket</th>
                                    <th>Programmer</th>
                                    <th>Deskripsi Permintaan</th>
                                    <th>Dokumen</th>
                                    <th>Persentase</th>
                                    <th class="text-center">Tindakan</th>
                                </tr>
                            </thead>
                            <tbody style="background: rgba(231,231,231,0.64);" id="auto">

                                <?php
                                if($this->data != null){
                                foreach ($this->data as $data) {
                                    echo "<tr>";
                                    echo "<td align='center'>" . $data['tanggal'] . "</td>";
                                    echo "<td align='center'>" . $data['jam'] . "</td>";
                                    echo "<td align='center'>" . $data['no_tiket'] . "</td>";
                                    echo "<td>";
                                    foreach ($data['list_tim'] as $y) {
                                        echo '<div> -' . $y['nama'] . '</div>';
                                    }
                                    echo "</td>";
                                    echo "<td>" . $data['judul_permintaan'] . "</td>";
                                    echo "<td align='center'>";
                                    if($data['dokumen_lampiran']){
                                        foreach ($data['dokumen_lampiran'] as $i) {
                                            echo '<div><a target="_blank" href="' . "/storage/index/dokumen-lampiran/{$i['doc_name']}/ext/{$i['ext']}" . '"><i class="fa-regular fa-file fs-4 ms-2"></i></a></div>';
                                        }
                                    }
                                    echo "</td>";

                                    echo "<td class='text-center'>" . $data['persentase'] . "%</td>";

                                    echo "<td align='center' background: rgb(223,78,87);>";
                                    echo "<a class='btn text-white' type='button' style='margin: 13px;background: rgb(53,168,184);' href='/programmer/permintaan/detail/" . $data[id_tiket] . "'>DETAIL</a>";
                                    echo "<a class='btn text-white' type='button' style='margin: 13px;background: #ffc107;' href='/programmer/project/id_tiket/" . $data[id_tiket] . "'>PROYEK</a>";
                                    // if ($data['id_status_tiket'] != 6 && (!$data['reference_to'])) {
                                    // }
                                    echo "</td>";
                                    echo "</tr>";
                                }
                                }
                                
                                ?>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- /.content -->