<!-- Main content -->
<section class="content">

    <!-- Modal -->
    <div class="modal fade" id="edit" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="exampleModalLabel">Edit Sub-tahapan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form class="needs-validation" method="post" action="/programmer/edit-Sub-Tahapan" novalidate>
                        <div class="d-none">
                            <div class="mb-3"><label class="form-label"><strong>ID TIKET</strong><br /></label><input id="id" name="id_tiket" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tiket'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TAHAPAN</strong><br /></label><input id="id" name="id_tahapan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tahapan'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID SUB TAHAPAN</strong><br /></label><input id="id_sub" name="id_sub_tahapan" class="form-control" type="text" style="border-radius: 10px;" /></div>
                        </div>
                        <div class="mb-3">
                            <label for="sub" class="form-label"><strong>Nama Sub-tahapan</strong><br /></label>
                            <input id="sub" name="sub_tahapan" class="form-control" type="text" style="border-radius: 10px;" required />
                            <div class="invalid-feedback">
                                Tolong isi nama sub-tahapan!
                            </div>
                            <div class="valid-feedback">
                                Baik!
                            </div>
                        </div>
                        <div class="d-flex align-items-end justify-content-end">
                            <button class="btn text-white m-2" style="background-color: #34abbb;"><i class="fa-regular fa-square-check"></i> Edit</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button> -->
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="tambah" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="exampleModalLabel">Tambah Sub-tahapan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" class="needs-validation" action="/programmer/tambah-Sub-Tahapan" novalidate>
                        <div class="d-none">
                            <div class="mb-3"><label class="form-label"><strong>ID TIKET</strong><br /></label><input id="id" name="id_tiket" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tiket'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TAHAPAN</strong><br /></label><input id="id" name="id_tahapan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tahapan'] ?>" /></div>
                        </div>
                        <div class="mb-3">
                            <label for="SubVali" class="form-label"><strong>Nama Sub-tahapan</strong><br /></label>
                            <input id="SubVali" name="sub_tahapan" class="form-control" type="text" style="border-radius: 10px;" required />
                            <div class="invalid-feedback">
                                Tolong isi nama sub-tahapan!
                            </div>
                            <div class="valid-feedback">
                                Baik!
                            </div>
                        </div>
                        <div class="d-flex align-items-end justify-content-end">
                            <button class="btn text-white m-2" style="background-color: #34abbb;"><i class="fa-regular fa-square-check"></i> Tambah</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button> -->
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="delete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="exampleModalLabel">Hapus Sub-tahapan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" action="/programmer/hapus-Sub-Tahapan">
                        <div class="d-none">
                            <div class="mb-3"><label class="form-label"><strong>ID TIKET</strong><br /></label><input id="id" name="id_tiket" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tiket'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TAHAPAN</strong><br /></label><input id="id" name="id_tahapan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tahapan'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID SUB TAHAPAN</strong><br /></label><input id="id_sub" name="id_sub_tahapan" class="form-control" type="text" style="border-radius: 10px;" /></div>
                        </div>
                        <div class="text-center mb-2">
                            Apakah anda yakin ingin menghapus Sub-tahapan ini ?
                        </div>
                        <div class="d-flex align-items-end justify-content-center">
                            <a class="btn text-white m-2" style="background-color: #34abbb;" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i> Batal</a>
                            <button class="btn text-white m-2" style="background-color: red;"><i class="fa-regular fa-square-check"></i> Hapus</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button> -->
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="edit-todo" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="exampleModalLabel">Edit Todo List</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" class="needs-validation" action="/programmer/edit-Todo-List" novalidate>
                        <div class="d-none">
                            <div class="mb-3"><label class="form-label"><strong>ID TIKET</strong><br /></label><input id="id" name="id_tiket" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tiket'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TAHAPAN</strong><br /></label><input id="id" name="id_tahapan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tahapan'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TODO LIST</strong><br /></label><input id="id-todo" name="id_todo_list" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tahapan'] ?>" /></div>
                        </div>
                        <div class="mb-3">
                            <label for="todo" class="form-label"><strong>Nama Todo List</strong><br /></label>
                            <input id="todo" name="todo_list" class="form-control" type="text" style="border-radius: 10px;" required />
                            <div class="invalid-feedback">
                                Tolong isi nama todo-list!
                            </div>
                            <div class="valid-feedback">
                                Baik!
                            </div>
                        </div>
                        <div class="d-flex align-items-end justify-content-end">
                            <button class="btn text-white m-2" style="background-color: #34abbb;"><i class="fa-regular fa-square-check"></i> Edit</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button> -->
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="tambah-todo" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="exampleModalLabel">Tambah Todo List</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" class="needs-validation" action="/programmer/tambah-Todo-List" novalidate>
                        <div class="d-none">
                            <div class="mb-3"><label class="form-label"><strong>ID TIKET</strong><br /></label><input id="id" name="id_tiket" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tiket'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TAHAPAN</strong><br /></label><input id="id" name="id_tahapan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tahapan'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID SUB TAHAPAN</strong><br /></label><input id="id_sub" name="id_sub_tahapan" class="form-control" type="text" style="border-radius: 10px;" /></div>
                        </div>
                        <div class="mb-3">
                            <label for="valitodo" class="form-label"><strong>Nama Todo List</strong><br /></label>
                            <input id="valitodo" name="todo_list" class="form-control" type="text" style="border-radius: 10px;" required />
                            <div class="invalid-feedback">
                                Tolong isi nama todo-list!
                            </div>
                            <div class="valid-feedback">
                                Baik!
                            </div>
                        </div>
                        <div class="d-flex align-items-end justify-content-end">
                            <button class="btn text-white m-2" style="background-color: #34abbb;"><i class="fa-regular fa-square-check"></i> Tambah</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button> -->
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="delete-todo" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="exampleModalLabel">Hapus Todo-list</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" action="/programmer/hapus-Todo-List">
                        <div class="d-none">
                            <div class="mb-3"><label class="form-label"><strong>ID TIKET</strong><br /></label><input id="id" name="id_tiket" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tiket'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TAHAPAN</strong><br /></label><input id="id" name="id_tahapan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tahapan'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TODO LIST</strong><br /></label><input id="id_todo" name="id_todo_list" class="form-control" type="text" style="border-radius: 10px;" /></div>
                        </div>
                        <div class="text-center mb-2">
                            Apakah anda yakin ingin menghapus Todo List ini ?
                        </div>
                        <div class="d-flex align-items-end justify-content-center">
                            <a class="btn text-white m-2" style="background-color: #34abbb;" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i> Batal</a>
                            <button class="btn text-white m-2" style="background-color: red;"><i class="fa-regular fa-square-check"></i> Hapus</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button> -->
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="revisi" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="exampleModalLabel">Revisi Todo-List</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" class="needs-validation" action="/programmer/revisi-Todo-List" novalidate>
                        <div class="d-none">
                            <div class="mb-3"><label class="form-label"><strong>ID TIKET</strong><br /></label><input id="id" name="id_tiket" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tiket'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TAHAPAN</strong><br /></label><input id="id" name="id_tahapan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tahapan'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TODO LIST</strong><br /></label><input id="id_todo" name="id_todo_list" class="form-control" type="text" style="border-radius: 10px;" /></div>
                        </div>
                        <label for="alamat" class="form-label fw-normal">Keterangan</label>
                        <textarea class="form-control" id="alamat" rows="4" placeholder="Keterangan Revisi" name="deskripsi_revisi" required></textarea>
                        <div class="invalid-feedback">
                            Tolong isi keterangan sebelum submit revisi!
                        </div>
                        <div class="valid-feedback">
                            Baik!
                        </div>
                        <div class="text-center my-2">
                            Apakah anda yakin melakukan revisi untuk Todo List ini ?
                        </div>
                        <div class="d-flex align-items-end justify-content-center">
                            <a class="btn text-white m-2" style="background-color: #34abbb;" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i> Batal</a>
                            <button class="btn text-white m-2" style="background-color: red;"><i class="fa-regular fa-square-check"></i> Revisi</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="laporan" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="exampleModalLabel">Laporan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" class="needs-validation" action="/programmer/selesai-Todo-List" enctype="multipart/form-data" novalidate>
                        <div class="d-none">
                            <div class="mb-3"><label class="form-label"><strong>ID TIKET</strong><br /></label><input id="id" name="id_tiket" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tiket'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TAHAPAN</strong><br /></label><input id="id" name="id_tahapan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['id_tahapan'] ?>" /></div>
                            <div class="mb-3"><label class="form-label"><strong>ID TODO LIST</strong><br /></label><input id="id_todo" name="id_todo_list" class="form-control" type="text" style="border-radius: 10px;" /></div>
                        </div>
                        <label for="alamat" class="form-label fw-normal fw-bold">Keterangan</label>
                        <textarea class="form-control" id="alamat" rows="4" placeholder="Keterangan Laporan" name="keterangan" required></textarea>
                        <div class="invalid-feedback">
                            Tolong isi keterangan sebelum submit laporan!
                        </div>
                        <div class="valid-feedback">
                            Baik!
                        </div>
                        <div class="mb-3">
                            <label for="jenis" class="form-label"><strong>Jenis Dokumen</strong><br /></label>
                            <select class="form-select" name="id_jenis_dokumen" id="jenis" required>
                                <?php
                                echo '<option disabled selected value> -- Tentukan Pilihan -- </option>';
                                foreach ($this->data['list_jenis_dokumen'] as $data) {
                                    echo '<option value="' . $data['id'] . '">' . $data['jenis_dokumen'] . '</option>';
                                }
                                ?>
                            </select>
                            <div class="invalid-feedback">
                                Tolong pilih jenis Dokumen!
                            </div>
                            <div class="valid-feedback">
                                Baik!
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="formFile" class="form-label">Lampirkan Dokumen</label>
                            <input class="form-control" multiple="multiple" type="file" id="formFile" name="dokumen" required>
                            <div class="invalid-feedback">Tolong lampirkan dokumen!</div>
                            <div class="valid-feedback">
                                Baik!
                            </div>
                        </div>
                        <div class="d-flex align-items-center justify-content-end">
                            <a class="btn text-white m-2" style="background-color: #34abbb;" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i> Batal</a>
                            <button class="btn text-white m-2 bg-success"><i class="fa-regular fa-square-check"></i> Lapor</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container-fluid">
            <h3 class="text-dark mb-4">List Progress Tahapan <?= $this->data['nama_tahapan'] ?></h3>
            <div class="card shadow" style="border-bottom-right-radius: 15px;border-top-right-radius: 15px;border-top-left-radius: 15px;border-bottom-left-radius: 15px;">
                <div class="card-header py-3" style="border-top-left-radius: 15px;border-top-right-radius: 15px;">
                    <div class="row">
                        <div class="col-md-12 col-lg-12 ">
                            <p class="text-primary m-0 fw-bold">Harap menentukan sub-tahapan terlebih dahulu sebelum menentukan todo-list untuk proyek</p>
                        </div>

                    </div>
                </div>
                <div class="card-body row">
                    <div class="tahapan">

                        <div class="row thp-all">
                            <div class="col-lg-12 col-xxl-12">
                                <div class="card-header px-1 row" style="background: rgb(255,255,255);border-top-left-radius: 15px;border-top-right-radius: 15px;border-width: 0px;">
                                    <h3 class="fw-bold nama-tahap col-md-6"><i class="fa-solid fa-file-circle-check"></i><?= $this->data['nama_tahapan'] ?></h3>
                                    <div class="col-md-6 d-flex align-items-center justify-content-end">
                                        <!-- <input class="sub-thp" type='text' placeholder="Sub-tahapan"> -->
                                        <button class="btn push btn-primary ms-2" data-bs-toggle="modal" data-bs-target="#tambah">Tambah Sub-tahapan</button>
                                    </div>
                                </div>
                                <div class="card shadow mb-3" style="border-radius: 15px;">
                                    <div class="card-body" style="background: rgba(0,0,0,0.19);border-radius: 15px;">
                                        <h4 class="small fw-bold">Progress<span class="float-end progressbar-label"></span></h4>
                                        <div class="progressbar-container">
                                            <div class="progressbar-bar "></div>
                                        </div>
                                        <form>
                                            <div class="row ">
                                                <div class="col">
                                                    <!-- daftar tahapan -->
                                                    <div>
                                                        <!-- panggil id subtahapan disini -->
                                                        <div class="accordion tasks">
                                                            <!-- isi data yang diolah dasi js -->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

<!-- /.content -->