<?php
$notif = null;
if (Zend_Auth::getInstance()->hasIdentity())
  $notif  = (new Dpr_NotifikasiService)->getDataWithLimit(Zend_Auth::getInstance()->getIdentity()->id, 3);
?>
<style>
  .flex-center {
    display: flex;
    justify-content: center;
    align-items: center;
  }


  .social-links {
    display: flex;
  }

  .social-btn {
    cursor: pointer;
    height: 50px;
    width: 50px;
    font-family: "Titillium Web", sans-serif;
    color: #333;
    border-radius: 10px;
    box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.1);
    background: white;
    margin: 5px;
    transition: 1s;
  }

  .social-btn span {
    width: 0px;
    overflow: hidden;
    transition: 1s;
    text-align: center;
  }

  .social-btn:hover {
    width: 150px;
    border-radius: 5px;
  }

  .social-btn:hover span {
    padding: 2px;
    width: max-content;
  }
</style>
<div class="row">
  <div class="col-lg-12 col-xxl-12">

    <div class="card shadow mb-0" style="border-radius: 15px;">
      <div class="card-body">
        <div>
          <p class="text-primary m-0 fw-bold" style="padding-bottom: 10px;">Keterangan :</p>
        </div>
        <form>
          <div class="row">
            <div class="col-md-4 col-sm-12">
              <div class="col">
                <!-- <div class="mb-3"><label class="form-label"><strong>Judul</strong><br /></label><input id="judul" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['judul'] ?>" disabled /></div> -->
                <div class="mb-3"><label class="form-label"><strong>Pelapor</strong><br /></label><input id="pelapor" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['nama'] ?>" disabled /></div>
                <div class="mb-3"><label class="form-label"><strong>Unit Kerja</strong><br /></label><input id="Unit Kerja" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['unit_kerja'] ?>" disabled /></div>
                <div class="mb-3"><label class="form-label"><strong>HP</strong><br /></label><input id="hp" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['hp'] ?>" disabled /></div>
                <div class="mb-3"><label class="form-label"><strong>Email</strong><br /></label><input id="email" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['email'] ?>" disabled /></div>
              </div>
            </div>
            <div class="col">
              <div class="row">
                <div class="col">
                  <div class="mb-3"><label class="form-label"><strong>Bagian</strong><br /></label><input id="bagian" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['jabatan'] ?>" disabled /></div>
                </div>
                <div class="col">
                  <div class="mb-3"><label class="form-label"><strong>Gedung</strong></label><input id="gedung" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['gedung'] ?>" disabled /></div>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <div class="mb-3"><label class="form-label"><strong>Lantai</strong></label><input id="lantai" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['lantai'] ?>" disabled /></div>
                </div>
                <div class="col">
                  <div class="mb-3"><label class="form-label"><strong>Ruangan</strong></label><input id="ruangan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['ruangan'] ?>" disabled /></div>
                </div>
              </div>




              <div class="mb-3"><label class="form-label"><strong>Kategori</strong></label><input id="ruangan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['kategori'] ?>" disabled /></div>
              <div class="mb-3">
                <? if ($this->data['dokumen_lampiran'] != null) { ?>
                  <label class="form-label"><strong>Dokumen Lampiran</strong></label><br>
                  <? foreach ($this->data['dokumen_lampiran'] as $data) { ?>
                    <a href="/storage/index/dokumen-lampiran/<?= $data['doc_name'] . '/ext/' . $data['ext'] ?>" target="_blank"><i class="fa-regular fa-file" style="font-size: 40px;"></i></a>
                <? }
                } ?>
              </div>
              <div class="mb-3"><label class="form-label"><strong>Keterangan</strong><br /></label><textarea id="keterangan" class="form-control" rows="5" name="signature" style="border-radius: 15px;" disabled><?= $this->data['keterangan'] ?></textarea></div>

            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- button tindakan -->
<div class="row" id="button-tindakan-helpdesk">
  <div class="col d-flex justify-content-center flex">
    <div class='social-btn flex-center' data-toggle="modal" data-target="#modal-solusi" id="" style="background-color:#ebc95d;">
      <i class="far fa-flag"></i><span>Selesai</span>
    </div>
    <div class='social-btn flex-center' data-toggle="modal" data-target="#modal-terkendala" id="" style="background-color:#ebc95d;">
      <i class="far fa-lightbulb"></i><span>Terkendala</span>
    </div>
  </div>
</div>
<!-- close Button Tindakan -->
<!-- button kerjakan -->
<div class="row" id="button-kerjakan-helpdesk">
  <div class="col d-flex justify-content-center flex">
    <form method="post" action="/helpdesk/kerjakan/">
      <input type="hidden" name="id_tiket" value="<?= $this->data['id'] ?>">
      <button type="submit" class='btn social-btn flex-center' onClick="refreshPage()" style="background-color:#ebc95d;">
        <i class="fa-solid fa-rocket"></i><span>Kerjakan</span>
      </button>
    </form>
  </div>
</div>
<!-- close Button Kerjakan -->
<!-- laporan petugas -->
<div class="card shadow mt-3" style="border-bottom-right-radius: 15px;border-top-right-radius: 15px;border-top-left-radius: 15px;border-bottom-left-radius: 15px;">
  <div class="card-header ">
    <p class="text-primary m-0 fw-bold">Laporan Petugas</p>
  </div>
  <div class="card-body">
    <div class="table-responsive table mt-2" id="" role="grid" aria-describedby="dataTable_info" style="background: var(--bs-table-bg);border-radius: 10px;">
      <table id="dataTable" class="table my-0">
        <thead style="background: rgba(208,204,204,0.76);">
          <tr>
            <th style="width:150px">Tanggal Input</th>
            <th>Petugas</th>
            <th>Permasalahan akhir</th>
            <th>Lampiran</th>
            <th>keterangan</th>
            <th>tipe laporan</th>
          </tr>
        </thead>
        <tbody style="background: rgba(231,231,231,0.64);">


          <?php
          if ($this->data['laporan_petugas'] == null) {
            # code...
          } else {
            foreach ($this->data['laporan_petugas'] as $data) {
              echo "<tr>";
              echo "<td>" . $data['tanggal_input'] . "</td>";
              echo "<td>" . $data['user_input'] . "</td>";
              echo "<td>" . $data['permasalahan_akhir'] . "</td>";
              // echo "<td>". $data['original_name'] . "</td>";
              //    if ($this->data['original_name'] != null){    
              //    foreach($this->data['original_name'] as $data){
              echo "<td>";
              if ($data['doc_name']) {
                echo "<a href='/storage/index/tiket-image-laporan/{$data['doc_name']}/ext/{$data['ext']}' target='_blank'>";
                echo "<i class='fa-regular fa-file' style='font-size: 40px;'>" . "</i>" . "</a>";
                echo "</td>";
              }
              //   }} 
              echo "<td>" . $data['solusi'] . "</td>";
              echo "<td>" . $data['tipe_laporan'] . "</td>";
              echo "</tr>";
            }
          }
          ?>

        </tbody>
      </table>
    </div>
  </div>
</div>
<!-- close laporan petugas -->

<!-- MOdal solusi  -->
<div class="modal fade" id="modal-terkendala">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Terkendala</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form class="needs-validation form-group" method="post" action="/helpdesk/update-terkendala/" enctype="multipart/form-data" novalidate>
          <input type="hidden" name="id" value="<?= $this->data['id'] ?>">

          <div class="mb-3"><label>Permasalahan Akhir</label><input name="permasalahan_akhir" id="" class="form-control" type="text" style="border-radius: 10px;" value="" required/></div>
          <div class="mb-3"><label>Keterangan Terkendala</label><textarea class="form-control" id="alamat" rows="4" name="solusi" placeholder="Solusi ...." required></textarea></div>
          <div class="mb-3"><label for="formFile" class="form-label">Lampirkan Dokumen</label>
            <input class="form-control" multiple="multiple" name="dokumen[]" type="file" id="formFile"required>
          </div>
          <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
            <button id="submit" type="submit" class="btn btn-primary">Simpan</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- End Modal Solusi -->

<!-- MOdal solusi  -->
<div class="modal fade" id="modal-solusi">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Solusi</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form class="needs-validation form-group" method="post" action="/helpdesk/update-selesai/" enctype="multipart/form-data" novalidate>
          <input type="hidden" name="id" value="<?= $this->data['id'] ?>">
          <div class="mb-3"><label>Permasalahan Akhir</label><input name="permasalahan_akhir" id="" class="form-control" type="text" style="border-radius: 10px;" value="" required></div>
          <div class="mb-3"><label>Solusi</label><textarea class="form-control" id="alamat" rows="4" name="solusi" placeholder="Solusi ...." required></textarea></div>
          <div class="mb-3"><label for="formFile" class="form-label">Lampirkan Dokumen</label>
            <input name="dokumen[]" multiple="multiple" class="form-control" type="file" id="formFile" required>
          </div>
          <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
            <button id="submit" type="submit"  class="btn btn-primary">Simpan</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- End Modal Terkenadal -->

<?php
//var_dump($this->data) 
?>
<script>
  function hideButtonKerjakan() {
    kerjakan = document.getElementById('button-kerjakan-helpdesk');
    //x.className = 'hide';
    kerjakan.style.display = 'none';
  }

  function showButtonKerjakan() {
    document.getElementById('button-kerjakan-helpdesk');
    //x.className = 'show';
    kerjakan.style.display = 'block';
  }

  function hideButtonTindakan() {
    tindakan = document.getElementById('button-tindakan-helpdesk');
    //x.className = 'hide';
   tindakan.style.display = 'none';
  }

  function showButtonTindakan() {
    document.getElementById('button-tindakan-helpdesk');
    //x.className = 'show';
    tindakan.style.display = 'block';
  }
  let statuss = "<?= $this->data['id_status_tiket_internal'] ?>";
  //let statuss = 7 ;
  hideButtonTindakan();
  hideButtonKerjakan();
  if (statuss == 5) {
    showButtonKerjakan();
  }
  if (statuss == 8) {
    showButtonTindakan();
  }

  function refreshPage() {
    window.location.reload();
  }



  // hide();
  // show();
</script>