<?php if($this->error){?>
<div class="fw-bold text-center fs-3">
    <?=$this->error?>
</div>
<?}else{ 
    rsort($this->result);
    foreach ($this->result as $result) { ?>
<div class="card shadow mb-3 mx-3" style="background: rgb(255 255 255 / 9%);border:0px ;border-radius:10px;">
    <div class="card-header"  style="background: rgb(52 172 188); border:0px;border-top-left-radius: 10px;border-top-right-radius: 10px;">
        <div class="row">
            <div class="col">
            <?php
           
            if ($result['id_status_tiket'] == 1){
                echo"<i class='fa-solid fa-clipboard-list' style='font-size: 30px;color: #2816b9;'></i>";
            }if ($result['id_status_tiket'] == 6){
                echo"<i class='fa-regular fa-circle-check' style='font-size: 30px;color: #38fa35;'></i>";
            }if ($result['id_status_tiket'] > 1 && $result['id_status_tiket'] < 6){
                echo"<i class='fa-solid fa-person-running' style='font-size: 30px;color: #fabf35;'></i>";
            }if ($result['id_status_tiket'] == 7){
                echo"<i class='fa-regular fa-hourglass-half' style='font-size: 30px;color: #dfe8ff;'></i>";
            }if ($result['id_status_tiket'] > 7){
                echo"<i class='fas fa-shipping-fast' style='font-size: 30px;'></i>";
            }
            ?>  
            </div>
            <div class="col text-end">
                <?php if ($result['rating']) { 
                echo "<span class='stars' data-rating='$result[rating]' data-num-stars='5'>as</span>";
                }?>
            </div>
        </div>
    </div>
    <div class="card-body" style="background: rgb(255 255 255); border-bottom-left-radius: 10px;border-bottom-right-radius: 10px;">
        <div class="row">
            <div class="col-sm-8 col-lg-8 col-xl-9 col-xxl-9">
                <p class="text-secondary m-0 fw-bold">Kode tiket&nbsp;&nbsp;&emsp;: <?= $result['no_tiket'] ?></p>
                <p class="text-secondary m-0 fw-bold">Status tiket&emsp;: <?= $result['status_tiket'] ?></p>
                <p class="text-secondary m-0 fw-bold">Keterangan&emsp;: <?= $result['judul_permasalahan'] ?></p>
                <? if ($result['solusi']) : ?>
                <p class="text-secondary m-0 fw-bold">Solusi&nbsp;&nbsp;&nbsp;&emsp;&emsp;&emsp;: <?= $result['solusi'] ?></p>
                <? endif; ?>
                <!-- <label class="form-label">Keterangan : </label> -->
                <!-- <p><?= $result['judul_permasalahan'] ?></p> -->
            </div>
            <div class="col text-end mb-1">
                <?php if ($result['list_petugas']){foreach($result['list_petugas'] as $petugas){ ?>
                <img class="rounded-circle mr-1" src="<?= $petugas['profile']?>" width="52" height="52" data-toggle="tooltip" title="<?= $petugas['nama'] ?>"/>
                <?php }}?>
            </div>
        </div>
        <div class="row">
            <div class="col-4 col-md-6 d-flex align-items-end">
                <p class="text-primary m-0 fw-bold"><?= substr($result['jam'],0,5)?> | <?= $result['tanggal_huruf'][0] ?></p>
            </div>
            <div class="col-8 col-md-6 text-end">
            <? if ($result['id_status_tiket'] == 6 && !$result['rating']) { ?>
            <button class="btn btn-primary mx-2" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal<?= $result['no_tiket'] ?>" style="background-color:#34abbb">Beri Nilai</button>
            <? } ?>
            <button class="btn btn-primary"onclick="location.href='/tiket/status/id/ <?= $result['id'] ?>'" type="button"style="background-color:#34abbb" >Detail</button></div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal<?= $result['no_tiket'] ?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered ">
                <div class="modal-content" style="border-radius:20px">
                  <div class="modal-header" >
                    <span><h5 class="modal-title" id="exampleModalLabel">Rating Petugas</h5><p class="modal-title" id="exampleModalLabel">Kode Tiket : <?= $result['no_tiket'] ?></p></span>
                    <!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
                  </div>
                  <div class="modal-body" >
                    <form method="post" action="/tiket/beri-rating">
                    <input type="hidden" name="id_tiket" value="<?= $result['id']?>">  
                
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">  
                                <div class="d-md-flex justify-content-md-center align-items-md-center">
                                    <h5>Bagaimana Performa Pekerjaan Operator?</h5>
                                </div>
                            </div>
                            <div class="col-md-12">  
                                <div class="d-md-flex justify-content-md-center align-items-md-center">
                                    <div class="rating">
                                        <input type="radio" id="5<?= $result['no_tiket'] ?>" name="rating" value="5" />
                                        <label class="" for="5<?= $result['no_tiket'] ?>" title="Awesome" aria-hidden="true"></label>
                                        <input type="radio" id="4<?= $result['no_tiket'] ?>" name="rating" value="4" />
                                        <label class="" for="4<?= $result['no_tiket'] ?>" title="Great" aria-hidden="true"></label>
                                        <input type="radio" id="3<?= $result['no_tiket'] ?>" name="rating" value="3" />
                                        <label class="" for="3<?= $result['no_tiket'] ?>" title="Very good" aria-hidden="true"></label>
                                        <input type="radio" id="2<?= $result['no_tiket'] ?>" name="rating" value="2" />
                                        <label class="" for="2<?= $result['no_tiket'] ?>" title="Good" aria-hidden="true"></label>
                                        <input type="radio" id="1<?= $result['no_tiket'] ?>" name="rating" value="1" />
                                        <label class="" for="1<?= $result['no_tiket'] ?>" title="Bad" aria-hidden="true"></label>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                  </div>
                  <div class="modal-footer" style="border:0px">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Beri Nilai</button>
                  </div>
                  </form>
                </div>
              </div>
            </div>
        <!-- close Modal -->
<?php }
} ?>
<!-- batas -->


<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();   
});
</script>