
    <div class="card shadow"  style="border-bottom-right-radius: 15px;border-top-right-radius: 15px;border-top-left-radius: 15px;border-bottom-left-radius: 15px;">
        <!-- <div class="card-header py-3">
            <p class="text-primary m-0 fw-bold">Daftar Petugas</p>
        </div> -->
        <div class="card-body">
            <div class="table-responsive table" id="" role="grid" aria-describedby="dataTable_info" style="background: var(--bs-table-bg);border-radius: 10px;">
                <table id="petugas" class="table table-striped">
                    <thead style="background: rgba(208,204,204,0.76);">
                        <tr>
                            <th class="text-center">Id Petugas</th>
                            <th class="text-center">Nama</th>
                            <th class="text-center">Peran</th>
                            <th class="text-center">Status</th>
                        </tr>
                    </thead>
                    <tbody style="background: rgba(231,231,231,0.64);">    
                            <?php  
                            if ($this->data== null) {
                              # code...
                            }else{
		                          foreach($this->data as $data)
		                          { echo"<tr>";
		                        echo "<td align='center'>". $data['id'] . "</td>";
                                echo "<td align='center'>". $data['nama'] . "</td>";
                                echo "<td align='center'>". $data['peran'] . "</td>";
                                echo "<td align='center'>". $data['status'] . "</td>";
		                          }  }
		                          ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?php 
//var_dump($this->data)
?>