<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Fixed Sidebar</title>

 
  <link rel="stylesheet" href="/stela/css/all.min.css">
  <link rel="stylesheet" href="/stela/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/stela/css/select2.min.css">
  <link rel="stylesheet" href="/stela/css/jsgrid.min.css">
  <link rel="stylesheet" href="/stela/css/jsgrid-theme.min.css">
  <link rel="stylesheet" href="/stela/css/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand" style="background: linear-gradient(90deg, #457B92 0%, #34ACBC 100%);">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto"> 
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown pt-2">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>

      <li class="nav-item dropdown no-arrow ">
        <a class="nav-item dropdown no-arrow" data-toggle="dropdown" href="#">
          <img class="border rounded-circle w-75" src="/stela/assets/avatars/avatar1.jpeg" />
        </a>
        <div class="dropdown-menu ">
          <a href="#" class="dropdown-item">
            <i class="fas fa-users "></i> admin
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file "></i> Logout
          </a>
        </div>
      </li>
      <li class="nav-item pt-2">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar " style="background-color:#34ACBC;">
    <!-- Brand Logo -->
    <a href="index3.html" class="" style="background-color:#34ACBC">
      <span class="brand-text pl-5" ><img src="/stela/assets/logostela.png" width="152" height="67"></span>
    </a>
      <!-- Sidebar Menu -->
      <nav class="mt-2 sidebar ">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item ">
            <a href="#" class="nav-link text-light">
              <i class="nav-icon fas fa-user-cog"></i>
              <p>
                Daftar Petugas
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="index.html" class="nav-link text-light">
                  <i class="fas fa-user-secret nav-icon"></i>
                  <p>Operator Singa rusia</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="index2.html" class="nav-link text-light">
                  <i class="fas fa-user-ninja nav-icon"></i>
                  <p>Help Desk</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="index3.html" class="nav-link text-light">
                  <i class="fas fa-tools nav-icon"></i>
                  <p>IT Spesialist</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="" class="nav-link text-light">
              <i class="nav-icon fas fa-clipboard-list"></i>
              <p>
                Daftar Permintaan 
                
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="" class="nav-link text-light">
              <i class="nav-icon fas fa-chart-line"></i>
              <p>
                Statistik
                
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="" class="nav-link text-light">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Widgets
                
              </p>
            </a>
          </li>
          
            </ul>
          </li>
          
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper pt-4 mt-5 pb-5">
    <!-- Content Header (Page header) -->
    
        <!-- Main content -->
        <section class="content">
      <div class="container-fluid">
        <h3 class="text-dark mb-4">Daftar Permintaan</h3>
        <div class="card shadow" style="border-bottom-right-radius: 15px;border-top-right-radius: 15px;border-top-left-radius: 15px;border-bottom-left-radius: 15px;">
            <div class="card-header py-3" style="border-top-left-radius: 15px;border-top-right-radius: 15px;">
                <div class="row">
                    <div class="col-4 col-sm-4 col-lg-5 col-xl-6 col-xxl-6">
                        <p class="text-primary m-0 fw-bold">All Ticket</p>
                    </div>
                    <div class="col-3 col-sm-4 offset-0 d-flex justify-content-end">
                        <div class="text-md-end dataTables_filter" id="dataTable_filter-2">
                            <form class="d-none d-sm-inline-block me-auto ms-md-3 my-2 my-md-0 mw-100 navbar-search">
                                <div class="input-group" style="border-width: 22px;">
                                    <input  name="filter" id="filter-box" class="form-control border-0 small" type="text" placeholder="Search for ..." style="background-color:rgba(178, 178, 179, 0.39);">
                                    <button class="btn btn-secondary py-0" type="button" style="background: rgb(54,166,183);"><i class="fas fa-search"></i></button></div>
                            </form>
                            
                        </div>
                    </div>
                    <div class="col-5 col-sm-4 col-md-4 col-lg-3 col-xl-2 col-xxl-2 offset-0 d-flex justify-content-center"><button class="btn btn-secondary" onclick="location.href='/servicedesk/buat-tiket/'" style="background: rgb(53,167,184);">Buat Tiket</button></div>
                </div>
                <div class="row">
                <div id="pager" class="pt-2 ">
                    <form>
                      
                       <i class="first fas fa-angle-double-left"></i>
                       <i class="prev fas fa-angle-left"></i>
                       <input type="text" class="pagedisplay" disabled style="width:150px"/>
                       <i class="next fas fa-angle-right"></i>
                       <i class="last fas fa-angle-double-right"></i>
                       
                       <select class="pagesize custom-select" style="width:70px">
	                		<option value="5">5</option>
                      <option value="10">10</option>
                      <option selected="selected" value="15">15</option>
	                		<option value="20">20</option>
	                		<option value="30">30</option>
	                		<option value="40">40</option>
                  	   </select>
	                 	</form>
	                </div>  
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive table mt-2"  role="grid" aria-describedby="dataTable_info" style="background: var(--bs-table-bg);border-radius: 10px;">
                    <table class="table table-striped" id="myTable">
                        <thead style="background: rgba(208,204,204,0.76);">
                            <tr>
                                <th>Urgensi</th>
                                <th>kode tiket</th>
                                <th>Status</th>
                                <th>kategori</th>
                                <th>Tanggal</th>
                                <th>Petugas</th>
                                <th class="text-center">Tindakan</th>
                            </tr>
                        </thead>
                        <tbody style="background: rgba(231,231,231,0.64);" id="myTable">
                           
                            <?php
                            // $array_length = count($this->data);
                             rsort($this->data);
                            // $batas = 10;
                            // $halaman = isset($_GET['halaman']) ? (int)$_GET['halaman'] : 1;
                            // $halaman_awal = ($halaman > 1) ? ($halaman * $batas) - $batas : 0;

                            // $previous = $halaman - 1;
                            // $next = $halaman + 1;

                            // $jumlah_data = count($this->data);
                            // $total_halaman = ceil($jumlah_data / $batas);

                            // $this->data = array_slice($this->data, $halaman_awal, $batas);
                            // // $data_pegawai = mysqli_query($koneksi, "select * from pegawai limit $halaman_awal, $batas");
                            // $nomor = $halaman_awal + 1;
                            
		                          foreach($this->data as $data)
		                          {
                                
		                          	echo "<tr>";
		                          	echo "<td>". $data['urgensi'] ."</td>";
                                echo "<td>". $data['no_tiket'] ."</td>";
                                echo "<td>". $data['status_tiket'] ."</td>";
                                echo "<td>". $data['kategori'] ."</td>";
                                echo "<td>". $data['tanggal'] ."</td>";
                              
                               
                                if($data['list_petugas'])
                                {
                                echo"<td>";
                                foreach($data['list_petugas'] as $petugas){
                                 echo  $petugas['nama']. "<br>";
                                }
                                echo "</td>";
                              }else{
                                  echo "<td> </td>";
                                }
                              
		                          	echo "<td align='center'background: rgb(223,78,87);>";
		                          	echo "<a class='btn btn-secondary' type='button' style='margin: 13px;background: rgb(53,168,184);' href='/servicedesk/detail-permintaan/id/".$data[id]."'>DETAIL</a>";
		                          	
		                          	echo "</td>";
		                          	echo "</tr>";
                                
		                          }
		                          ?>
                                
                            <tr></tr>
                            <tr></tr>
                            <tr></tr>
                        </tbody>

                        <tfoot>
                            <tr></tr>
                        </tfoot>
                    </table>
                </div>
                <!-- <div class="row">
                                <div class="col-md-6 align-self-center">
                                    <p id="dataTable_info" class="dataTables_info" role="status" aria-live="polite">
                                        <?php echo "Showing " . ($halaman_awal+1) . " to " . $total_halaman . " of " . $jumlah_data;?>
                                    </p> 
                                </div>
                                <div class="col-md-6 pt-2">
                                    <nav class="d-lg-flex justify-content-lg-end dataTables_paginate paging_simple_numbers">
                                        <ul class="pagination justify-content-center">
                                            <li class="page-item">
                                                <a class="page-link" <?php if ($halaman > 1) {echo "href='?halaman=$Previous'";} ?>>Previous</a>
                                            </li>
                                            <?php for ($x = 1; $x <= $total_halaman; $x++) {?>
                                                <li class="page-item"><a class="page-link" href="?halaman=<?php echo $x ?>"><?php echo $x; ?></a></li>
                                            <?php } ?>
                                            <li class="page-item">
                                                <a class="page-link" <?php if ($halaman < $total_halaman) {echo "href='?halaman=$next'";} ?>>Next</a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                            </div> -->
            </div>
        </div>
    </div> 
    </section>
    <?php
   // var_dump($this->data);
    ?>
    
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    
    <strong>DPR RI 2022</strong> 
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<script src="/stela/js/jquery.min.js"></script>
<script src="/stela/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/stela/js/select2.full.min.js"></script>
<script src="/stela/js/adminlte.min.js"></script>
<script src="/stela/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/tablesorter.js"></script>
<script type="text/javascript" src="/js/jquery.tablesorter.pager.js"></script>
<script type="text/javascript" src="/js/tablesorter.js"></script>
<script type="text/javascript" src="/js/tablesorter_filter.js"></script>

<script type="text/javascript">
$(function() {
	$("#myTable").tablesorter({widthFixed: true, widgets: ['zebra']})
	.tablesorterPager({container: $("#pager"), positionFixed:false, size:15})
	.tablesorterFilter({filterContainer: $("#filter-box"),
   		filterWaitTime: 500,
   		filterColumns: [0,1,2,3,4,5,6]});
});
</script>

</body>
</html>

