    
<style>
       .flex-center {
    	display: flex;
    	justify-content: center;
    	align-items: center;
    }
    
    
    .social-links {
    	display: flex;
    }
    
    .social-btn {
    	cursor: pointer;
    	height: 50px;
    	width: 50px;
    	font-family: "Titillium Web", sans-serif;
    	color: #333;
    	border-radius: 10px;
    	box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.1);
    	background: white;
    	margin: 5px;
    	transition: 1s;
    }
    
    .social-btn span {
    	width: 0px;
    	overflow: hidden;
    	transition: 1s;
    	text-align: center;
    }
    
    .social-btn:hover {
    	width: 150px;
    	border-radius: 5px;
    }
    
    .social-btn:hover span {
    	padding: 2px;
    	width: max-content;
    }

</style>
    <div class="">
      <div class="col-lg-12 col-xxl-12">
        <div class="card shadow " style="border-radius: 15px;">
          <div class="card-body">
            <div class="row">
              <div class="col">
                <p class="text-primary m-0 fw-bold" style="padding-bottom: 10px;">Kode Tiket : <?= $this->data['no_tiket'] ?></p>
              </div>
              <div class="col-md-4 col-sm-12 text-end">
                <p class="text-primary m-0 fw-bold" style="padding-bottom: 10px;">Jam : 29.22 <?= $this->data['tanggal'] ?>&nbsp;| Tanggal : 21/09/2022 </p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-2 col-sm-12">
              <div class="mb-3"><label class="form-label"><strong>Via</strong><br /></label><input id="email" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['via'] ?>" disabled /></div>
              </div>
              <div class="col-md-2 col-sm-12">
              <div class="mb-3"><label class="form-label"><strong>Kategori</strong><br /></label><input id="email" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['sub_kategori'] ?>" disabled /></div>
              </div>
              <div class="col-md-2 col-sm-12">
              <div class="mb-3"><label class="form-label"><strong>Urgensi</strong><br /></label><input id="email" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['urgensi'] ?>" disabled /></div>
              </div>
              <div class="col-md-2 col-sm-12">
              <div class="mb-3"><label class="form-label"><strong>Status</strong><br /></label><input id="email" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['status_tiket'] ?>" disabled /></div>
              </div>
              <div class="col-md-4 col-sm-12">
              
              <? if ($this->data['petugas_aktif'] != null) { ?>
              <div class="mb-3"><label class="form-label"><strong>Petugas</strong></label><br />
              <!-- <textarea class='form-control' rows='2' name='signature' style='border-radius: 15px;' value='' disabled> -->
                  <?php foreach($this->data['petugas_aktif'] as $petugas){
                  echo  $petugas['nama']." (". $petugas['peran'].")";
                  echo "<br>";
                                    } ?>
                <!-- </textarea> -->
              <? } ?>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="">
        <div class="col-lg-12 col-xxl-12">

            <div class="card shadow " style="border-radius: 15px;">
                <div class="card-body">
                    <!-- <div>
                        <p class="text-primary m-0 fw-bold" style="padding-bottom: 10px;">Keterangan :</p>
                    </div> -->
                    <form>
                        <div class="row">
                            <div class="col-md-4 col-sm-12">
                              <div class="mb-3"><label class="form-label"><strong>Pelapor</strong><br /></label><input id="pelapor" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['pelapor'] ?>" disabled /></div>
                              <div class="mb-3"><label class="form-label"><strong>Unit Kerja</strong><br /></label><input id="Unit Kerja" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['unit_kerja'] ?>" disabled /></div>
                              <div class="mb-3"><label class="form-label"><strong>HP</strong><br /></label><input id="hp" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['hp'] ?>" disabled /></div>
                              <div class="mb-3"><label class="form-label"><strong>Email</strong><br /></label><input id="email" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['email'] ?>" disabled /></div>
                            </div>
                            <div class="col">
                              <div class="row">
                                <div class="col">
                                  <div class="mb-3"><label class="form-label"><strong>Keterangan</strong><br /></label><textarea id="keterangan" class="form-control" rows="" name="signature"  value=""style="border-radius: 15px; height: 126px;" disabled><?= $this->data['keterangan'] ?></textarea></div>
                                </div>
                              </div>
                              <div class="row">
                                <div class="col">
                                <div class="mb-3"><label class="form-label"><strong>Bagian</strong><br /></label><input id="bagian" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['bagian'] ?>" disabled /></div>
                                </div>
                                <div class="col">
                                <div class="mb-3"><label class="form-label"><strong>Gedung</strong></label><input id="gedung" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['gedung'] ?>" disabled /></div>
                                </div>
                              </div>
                              <div class="row">
                                <div class="col">
                                <div class="mb-3"><label class="form-label"><strong>Lantai</strong></label><input id="lantai" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['lantai'] ?>" disabled /></div>
                                </div>
                                <div class="col">
                                <div class="mb-3"><label class="form-label"><strong>Ruangan</strong></label><input id="ruangan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['ruangan'] ?>" disabled /></div>
                                </div>
                              </div>
                              <!-- <div class="row">
                                <div class="col">
                                <div class="mb-3"><label class="form-label"><strong>Kategori</strong></label><input id="ruangan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['urgensi'] ?>" disabled /></div>
                                </div>
                                <div class="col">
                                <div class="mb-3"><label class="form-label"><strong>Status</strong></label><input id="ruangan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->data['status_tiket_internal'] ?>" disabled /></div>
                                </div>
                              </div> -->
                              
                              
                                <div class="mb-3">
                                <? if ($this->data['dokumen_lampiran'] != null){ ?>
                                  <label class="form-label"><strong>Dokumen Lampiran</strong></label><br>
                                <? foreach($this->data['dokumen_lampiran'] as $data){?>
                                <a href="/storage/download/dokumen-lampiran/<?= $data['image_name'] ?>" target="_blank"><i class="fa-regular fa-file" style="font-size: 40px;"></i></a>
                                <? }} ?>
                                </div>
                            </div>   
                        </div>
                             
                      </form>
                    </div>
            </div>
        </div>
    </div>

  

    
    <div class="row">
      <div class="col d-flex justify-content-center flex">
        <div class='social-btn flex-center' data-toggle="modal" data-target="#modal-revisi-eskalasi" id="button-revisi-eskalasi" style="background-color:#c461bb;">
        <i class="fa-solid fa-user-plus"></i><span>Revisi Eskalasi</span>
        </div>
        <div class='social-btn flex-center' data-toggle="modal" data-target="#modal-revisi-kategori" id="button-revisi-kategori" style="background-color:#429bd6;">
          <i class="fas fa-boxes"></i><span>Revisi Kategori</span>
        </div>
      </div>
    </div>
      <!-- MOdal Revisi Eskalasi  -->
      <div class="modal fade" id="modal-revisi-eskalasi">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Revisi Eskalasi</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">

              <form class="needs-validation form-group" method="post" action="/servicedesk/update-eskalasi-revisi" onsubmit="return submitForm(this);" novalidate>
                <!-- <textarea id="keterangan" class="form-control" rows="2" name="signature" style="border-radius: 5px;" value="" disabled>
                  </textarea> -->
              <? if ($this->data['petugas_aktif'] != null) { ?>
              <div class="mb-3"><label>Petugas Eskalasi Sebelumnya</label></div>
              <table id="" class="table table-striped" style="border-radius:15px;">
                  <thead style="background: rgba(208,204,204,0.76);" >
                  <tr>
                    <th>nama</th>
                    <th>Peran</th>  
                    <th class="text-center">tindakan</th>  
                  </tr>
                  </thead>
                  <tbody>
                  <?php foreach($this->data['petugas_aktif'] as $petugas){
                  echo "<tr>";
                  echo "<td>". $petugas['nama'] ."</td>";
                  echo "<td>". $petugas['peran'] ."</td>";
                  echo "<td align='center'background: rgb(223,78,87);>";
                  echo "<a class='btn btn-secondary' type='button' style='background: rgb(53,168,184);' href='/servicedesk/delete-eskalasi/id_tiket/".$this->data['id']."/id_petugas/".$petugas['id']."'>Hapus</a>";
                  
                  echo "</td>";
                
                  echo "<tr>";
                                    } ?>
                  </tbody>
              </table>
              <? } ?>
              <input type="hidden" name="id" value="<?= $this-> data['id'] ?>">  
                <div>
                  <label>Beri Tugas</label>
                  <select class="select2"  name="eskalasi[]" multiple="multiple" data-placeholder="Pilih Petugas" style="width: 100%;" required>
                  <?php
                  foreach($this->data['list_eskalasi'] as $data)
                  {
                    
                    echo '<option value="' . $data['id'] . '">' . $data['nama'] . " (" . $data['peran'] .  ')</option>';
                    //if($data['id'] == $leaddetails[0]['city']){echo "selected";}
                  }
                  ?>
                  </select>
                  <div class="invalid-feedback">
                    Bagian Ini Tidak Boleh Kosong!
                  </div>
                  <div class="valid-feedback">
                    Baik!
                  </div>
                </div>
                
              
            
            <div class="modal-footer justify-content-between">
              <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
              <button type="submit" class="btn btn-primary" >Kirim</button>
              <!-- <button type="button" class="btn btn-primary" href="#konfirmasiEskalasi" data-toggle="modal">Kirim</button> -->
              
              
            </div>
            </form>
            </div>
          </div>
        </div>
      </div>
      <!-- End Modal Revisi Eskalasi -->    
      <!-- MOdal Revisi Eskalasi  -->
      <div class="modal fade" id="modal-revisi-kategori">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Revisi Kategori</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form class="form-group" method="post" action="/servicedesk/proses-revisi">
                <input type="hidden" name="id" value="<?= $this->data['id'] ?>">
                
                  <label for="id_via">Via</label>
                  <select class="required form-control select2" id="id_via" name="id_via" style="width: 100%;">
			            <option value=""> Pilih Via...</option>
			            <?php
			            foreach($this->data['list_via'] as $data)
			            {
			            	echo '<option value="' . $data['id'] . '"' . (($this->data['via'] == $data['via']) ? 'selected' : '') . '>' . $data['via'] .'</option>';
                  
                  }
			            ?>
                  </select>
                  
                  <label for="id_sub_kategori">Kategori</label>
                  <select class="required form-control select2" id="id_sub_kategori" name="id_sub_kategori" style="width: 100%;">
			            <option value=""> Pilih Kategori...</option>
			            <?php
			            foreach($this->data['list_sub_kategori'] as $data)
			            {
			            	echo '<option value="' . $data['id'] . '"' . (($this->data['sub_kategori']) && ($this->data['sub_kategori'] == $data['sub_kategori']) ? 'selected' : '') . '>' . $data['sub_kategori'] .'</option>';
                  
                  }
			            ?>
                  </select>

                  <label for="id_urgensi">Urgensi</label>
                  <select class="required form-control select2" id="id_urgensi" name="id_urgensi" style="width: 100%;">
			            <option value=""> Pilih Kategori...</option>
			            <?php
			            foreach($this->data['list_urgensi'] as $data)
			            {
			            	echo '<option value="' . $data['id'] . '"' . (($this->data['urgensi'] == $data['urgensi']) ? 'selected' : '') . '>' . $data['urgensi'] .'</option>';
                  
                  }
			            ?>
                  </select>
                  <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- End Modal Revisi Eskalasi -->    
  
      
<?php 
//var_dump($this->data);
//var_dump($petugas['id']);
?>
    <script>
// function konfirmasiFunction() {
//   alert("Yakin Ingin Melanjutkan?");
// }
function submitForm() {
  return confirm('Yakin ingin melanjutkan?');
}
</script>