
    <div class="row">
            <div class="col d-flex justify-content-center align-items-center">
                <div class="p-5" style="background:#c0e7ef;border-radius: 29px;">
                    <div class="text-center">
                        <h4 class="text-dark mb-4">Tiket berhasil Dibuat</h4>
                    </div>
                    <form class="justify-content-center align-items-center user">
                        <div class="mb-3"><input class="form-control form-control-user" value="<?= $this->no_tiket ?>" type="text" id="exampleInputEmail"  placeholder="" name="" style="border-radius: 15px;background: #f4f5f5;"></div>
                    </form>
                    <div class="text-center"></div>
                    <div class="text-center"></div>
                </div>
            </div>
    
        </div>
        <div class="card shadow-lg o-hidden border-0 my-5" style="background: rgba(255,255,255,0);">
            <div class="card-body p-0"></div>
        </div>
  