
    
    <div class="container">
        <div class="row">
            <div class="col-md-6 mt-5 home-content">
                <h1 class="fw-bold">Stela</h1>
                <p><br><span style="color: rgb(102, 102, 102);">Sistem Tiket dan Layanan atau bisa disingkat dengan STELA, merupakan sebuah aplikasi yang diperuntukkan bagi kalangan pegawai/staff internal DPR. Aplikasi ini merupakan sebuah sistem pelayanan baru yang dapat digunakan untuk melaporkan atau meminta layanan mengenai Teknologi dan Informasi di DPR RI yang kemudian akan dilakukan eskalasi oleh tim dari Pusat Teknologi dan Informasi (Pustekinfo)."</span><br><span style="color: rgb(102, 102, 102);"></span><br><span style="color: rgb(102, 102, 102);">.</span><br><br></p>
            </div>
            <div class="col-md-6 mt-5 justify-content-center align-items-center">
                <div class="row px-5">
                    <div class="col" style="--bs-light: #f8f9fa;--bs-light-rgb: 248,249,250;--bs-body-bg: #fff;border-radius: 20px;">
                        <form style="padding-left: 10%;padding-right: 10%;background: #ffffff;padding-bottom: 2px;padding-top: 0%;border-radius: 15px;" method="post" action="/beranda/lacak/">
                        <!-- <form style="padding-left: 10%;padding-right: 10%;background: #ffffff;padding-bottom: 2px;padding-top: 0%;border-radius: 15px;" method="get" action="/tiket/status"> -->
                            <h2 class="text-center pt-2 fw-bold">Lacak Status Permintaan</h2>
                            <div class="mb-3">
                                <label class="form-label" for="name" style="margin-bottom: 16px;font-size: 18px;color: #000000;padding-left: 0%;padding-right: 6%;text-align: center;width: 100%;">
                                    Masukkan Kode Tiket Permintaan
                                </label>
                                <input class="form-control item text-center" type="text" name="no_tiket" placeholder="Masukkan Kode" style="height: 50px;background: rgb(227,227,227);border-bottom-width: 2px;border-radius: 15px;">
                            </div>
                            <div class="mb-3 d-flex justify-content-center " >
                                <button type="submit" class="btn btn-primary btn-lg d-block " style="border-radius: 15px;background-color: #34abbb;" type="submit">
                                    Lacak Tiket
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row">
                    <div class="col" style="padding-top: 14px;">
                        <h2 class="fw-bold text-center">Belum Punya tiket?</h2>
                        <div class="mb-3 d-flex justify-content-center">
                            <button class="btn btn-primary btn-lg " style="border-radius: 15px;background-color: #34abbb;" onclick="location.href='/tiket'">
                                Buat Tiket Permintaan
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


