<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?= $this->title ?></title>
  <link rel="icon" href="/stela/assets/logostelatitle.png" type="image/x-icon">
 
  <link rel="stylesheet" href="/stela/css/all.min.css">
  <link rel="stylesheet" href="/stela/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/stela/css/select2.min.css">
  <link rel="stylesheet" href="/stela/css/adminlte.min.css">
  <link rel='stylesheet' href="/stela/css/rating.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="/stela/css/tablecss/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="/stela/css/tablecss/datatables-responsive/css/responsive.bootstrap4.min.css">

  <!-- get 3 notif user session -->
  <?php
  $notif = null;
  if (Zend_Auth::getInstance()->hasIdentity())
    $notif  = (new Dpr_NotifikasiService)->getDataWithLimit(Zend_Auth::getInstance()->getIdentity()->id, 3);
  ?>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">
  <!-- Site wrapper -->
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand" style="background: linear-gradient(90deg, #457B92 0%, #34ACBC 100%);">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>

      </ul>

      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown pt-2">
          <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-bell"></i>
            <?php if ($notif) { ?>
              <span class="badge badge-danger navbar-badge">!</span>
            <?php } ?>
          </a>
          <div class="dropdown-menu dropdown-menu-end dropdown-list animated--grow-in">
            <h6 class="dropdown-header">Notifikasi</h6>
            <?php if ($notif) : foreach ($notif as $v) : ?>
                <?php if (!$v->dibaca) : ?>
                  <a class="dropdown-item d-flex align-items-center" href="/notifikasi/read-notifikasi/id_notif/<?= $v->id ?>/nomor_tiket/<?= $v->no_tiket ?>">
                  <?php else : ?>
                    <a class="dropdown-item d-flex align-items-center" style="background: rgb(220 230 233 / 42%);" href="/notifikasi/read-notifikasi/id_notif/<?= $v->id ?>/nomor_tiket/<?= $v->no_tiket ?>">
                    <?php endif ?>
                    <div class="me-3">
                      <div class="bg-primary icon-circle"><i class="fas fa-file-alt text-white"></i>
                      </div>
                    </div>
                    <div>
                      <span class="small text-gray-500"><?= $v->tanggal ?></span>
                      <p><?= $v->no_tiket ?> - <?= $v->keterangan ?></p>
                    </div>
                    </a>
                  <?php endforeach;
              else : ?>
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    no data
                    <a>
                    <?php endif ?>
                    <a class="dropdown-item text-center small text-gray-500" href="/notifikasi/">Lihat Semua Notifikasi</a>
          </div>
        </li>

        <li class="nav-item dropdown no-arrow ">
          <a class="nav-item dropdown no-arrow" data-toggle="dropdown" href="#">
            <img class="border rounded-circle " width="50" height="50" src="<?= Zend_Auth::getInstance()->getIdentity()->profile ?>" />
          </a>
          <div class="dropdown-menu shadow dropdown-menu-end animated--grow-in">
            <? if (Zend_Auth::getInstance()->getIdentity()->nama_lengkap != null) { ?>
              <a class="dropdown-item" style="pointer-events: none;">
                <i class="fas fa-user fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;<?= Zend_Auth::getInstance()->getIdentity()->nama_lengkap ?>
              </a>
            <? } ?>
            <? if (Zend_Auth::getInstance()->getIdentity()->nama_lengkap == null) { ?>
              <a class="dropdown-item" href="/login">
                <i class="fas fa-list fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;login
              </a>
            <? } ?>
            <? if (Zend_Auth::getInstance()->getIdentity()->nama_lengkap != null) { ?>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/logout">
                <i class="fas fa-sign-out-alt fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Logout
              </a>
            <? } ?>
          </div>
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar " style="background-color:#34ACBC;">
      <!-- Brand Logo -->
      <a href="/" class="" style="background-color:#34ACBC">
        <span class="brand-text pl-5"><img src="/stela/assets/logostela.png" width="152" height="67"></span>
      </a>
      <!-- Sidebar Menu -->
      <nav class="mt-2 sidebar ">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

          <li class="nav-item ">
            <a href="/servicedesk/index" class="nav-link text-light ">
              <i class="nav-icon fas fa-chart-pie"></i>
              <p>
                Statistik
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview ">
              <li class="nav-item ">
                <a href="/viewer/index" class="nav-link text-light">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Statistik</p>
                </a>
              </li>
              <li class="nav-item ">
                <a href="/viewer/statistik-tahun" class="nav-link text-light">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Periode 1 Tahun</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/viewer/statistik-bulan" class="nav-link text-light">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Periode 1 Bulan</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/viewer/rekap-kecepatan-tiket" class="nav-link text-light">
                  <i class="nav-icon fas fa-clipboard-list"></i>
                  <p>
                    Rekap Durasi Tiket
                  </p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/viewer/rekap-petugas-tahun" class="nav-link text-light">
                  <i class="nav-icon fas fa-clipboard-list"></i>
                  <p>
                    Rekap Rating Petugas
                  </p>
                </a>
              </li>
                <li class="nav-item">
                <a href="/programmer" class="nav-link text-light">
                  <i class="nav-icon fas fa-clipboard-list"></i>
                  <p>
                    Rekap Singa Rusia
                  </p>
                </a>
              </li>
              <!-- <li class="nav-item">
                <a href="/servicedesk/statistik-hari" class="nav-link text-light">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Periode 1 Hari</p>
                </a>
              </li> -->
            </ul>
          </li>


        </ul>
      </nav>
      <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper pt-4 mt-5 pb-3">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
      <?= $this->layout()->content; ?>
    </section>
    <!-- /.content -->
  </div>
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">

    <strong>DPR RI 2022</strong>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
  </div>
  <!-- ./wrapper -->

  <script src="/stela/js/jquery.min.js"></script>
  <!-- <script src="/stela/bootstrap/js/bootstrap.min.js"></script> -->
  <script src="/stela/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/stela/js/select2.full.min.js"></script>
  <script src="/stela/js/adminlte.min.js"></script>
  <script src="/stela/js/Chart.min.js"></script>
  <script src="/stela/js/statistikstela.js"></script>



  <script src="/stela/js/table/datatables/jquery.dataTables.min.js"></script>
  <script src="/stela/js/table/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/stela/js/table/datatables-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/stela/js/table/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <script src="/stela/js/table/datatables-buttons/js/dataTables.buttons.min.js"></script>
  <script src="/stela/js/table/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
  <script src="/stela/js/table/jszip/jszip.min.js"></script>
  <script src="/stela/js/table/pdfmake/pdfmake.min.js"></script>
  <script src="/stela/js/table/pdfmake/vfs_fonts.js"></script>
  <script src="/stela/js/table/datatables-buttons/js/buttons.html5.min.js"></script>
  <script src="/stela/js/table/datatables-buttons/js/buttons.print.min.js"></script>
  <script src="/stela/js/table/datatables-buttons/js/buttons.colVis.min.js"></script>


  <!-- FLOT CHARTS -->
  <script src="../../plugins/flot/jquery.flot.js"></script>
  <!-- FLOT RESIZE PLUGIN - allows the chart to redraw when the window is resized -->
  <script src="../../plugins/flot/plugins/jquery.flot.resize.js"></script>
  <!-- FLOT PIE PLUGIN - also used to draw donut charts -->
  <script src="../../plugins/flot/plugins/jquery.flot.pie.js"></script>
  <script>
        function myFunction() {
            const invalidForm = document.querySelector('form:invalid');
            const submitBtn = document.getElementById('submit');
            console.log(invalidForm)
            if(invalidForm){
                submitBtn.disabled = false;
            }else {
                submitBtn.setAttribute('disabled', true);
            }
        }
    </script>
  <!-- notif -->
  <script>
    var audio = new Audio("/stela/assets/notif.mp3");

    function playAudio() {
      audio.autoplay = true;
      audio.load();
    }
    var oldDatas = null;

    function loadDoc() {
      var xhttp = new XMLHttpRequest();
      xhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
          const datas = JSON.parse(this.response);

          if (!oldDatas) {
            oldDatas = datas;
          } else {
            datas.map(e => {
              let isSame = false;
              oldDatas.map(v => {
                if (e.id == v.id) isSame = true;
              })
              if (!isSame) {
                playAudio();
                $(document).Toasts('create', {
                  icon: 'fas fa-envelope fa-lg',
                  title: e.keterangan,
                  subtitle: e.no_tiket,
                  body: '<a class="directions-link" href="/notifikasi/read-notifikasi/id_notif/">Lihat Tiket</a>',
                })
                $("a.directions-link").attr("href", $("a.directions-link").attr("href") + e.id + '/nomor_tiket/'+e.no_tiket);
              }
            })
            oldDatas = datas;
          }
        }
      };
      xhttp.open("GET", "/notifikasi/ajax", true);
      xhttp.send();

    }
    //loadDoc();
    setInterval(loadDoc, 1000);
  </script>
<!--  datatable-->
  <script>
      $(function() {
          $('#petugas').DataTable({
              "paging": true,
              "lengthChange": true,
              "searching": true,
              "ordering": true,
              "info": true,
              "autoWidth": false,
              "responsive": true,
              // order: [
              //     [0, 'desc']
              // ],
              "buttons": ["copy", "csv", "excel", "pdf", "print"]
          }).buttons().container().appendTo('#petugas_wrapper .col-md-6:eq(0)');
      });
  </script>

  <script>
    //-------------
    //- BAR CHART -
    //-------------
    var barChartCanvas = $('#barChart').get(0).getContext('2d')
    var barChartData = $.extend(true, {}, areaChartData)


    var barChartOptions = {
      responsive: true,
      maintainAspectRatio: false,
      datasetFill: false
    }

    new Chart(barChartCanvas, {
      type: 'bar',
      data: barChartData,
      options: barChartOptions
    })


    //-------------
    //- PIE CHART -
    //-------------
    // Get context with jQuery - using jQuery's .get() method.
    var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
    var pieData = donutData;
    var pieOptions = {
      maintainAspectRatio: false,
      responsive: true,
    }
    //Create pie or douhnut chart
    // You can switch between pie and douhnut using the method below.
    new Chart(pieChartCanvas, {
      type: 'pie',
      data: pieData,
      options: pieOptions
    })
  </script>
  <script>
    var barChartCanvas = $('#barChart1tahun').get(0).getContext('2d')
    var barChartData = $.extend(true, {}, data1tahun)


    var barChartOptions = {
      responsive: true,
      maintainAspectRatio: false,
      datasetFill: false
    }

    new Chart(barChartCanvas, {
      type: 'bar',
      data: barChartData,
      options: barChartOptions
    })
    var barChartCanvas = $('#barChart1bulan').get(0).getContext('2d')
    var barChartData = $.extend(true, {}, data1bulan)


    var barChartOptions = {
      responsive: true,
      maintainAspectRatio: false,
      datasetFill: false
    }

    new Chart(barChartCanvas, {
      type: 'bar',
      data: barChartData,
      options: barChartOptions
    })
    var barChartCanvas = $('#barChart1minggu').get(0).getContext('2d')
    var barChartData = $.extend(true, {}, data1minggu)
    var barChartOptions = {
      responsive: true,
      maintainAspectRatio: false,
      datasetFill: false
    }

    new Chart(barChartCanvas, {
      type: 'bar',
      data: barChartData,
      options: barChartOptions
    })
  </script>
  <!-- statisik bulan -->
  <script>
    let listdata = <?= json_encode($this->data['list_data']) ?>;
    //console.log(listdata);
    $(document).ready(function() {
      function dashboard(tahun, bulan) {
        //bulan = 'Desember'
        //$("#datatahunpilihan").text(`${listdata['All']['tiket']['Desember']}`); 
        $("#Singa-statistikbulan").text(`${listdata[tahun]['sub_kategori']['Singa Rusia'][bulan]}`);
        $("#Internet-statistikbulan").text(`${listdata[tahun]['sub_kategori']['Internet & Jaringan'][bulan]}`);
        $("#Sistem-statistikbulan").text(`${listdata[tahun]['sub_kategori']['Sistem Operasi'][bulan]}`);
        $("#Software-statistikbulan").text(`${listdata[tahun]['sub_kategori']['Software'][bulan]}`);
        $("#Hardware-statistikbulan").text(`${listdata[tahun]['sub_kategori']['Hardware'][bulan]}`);
        $("#Aplikasi-statistikbulan").text(`${listdata[tahun]['sub_kategori']['Aplikasi'][bulan]}`);
        $("#Pengembangan-statistikbulan").text(`${listdata[tahun]['sub_kategori']['Pengembangan Jaringan'][bulan]}`);
        $("#Lain-statistikbulan").text(`${listdata[tahun]['sub_kategori']['Lain-Lain'][bulan]}`);
        $("#Teleconference-statistikbulan").text(`${listdata[tahun]['sub_kategori']['Teleconference'][bulan]}`);
        $("#File-statistikbulan").text(`${listdata[tahun]['sub_kategori']['File Sharing dan Cloud'][bulan]}`);
        $("#Undangan-statistikbulan").text(`${listdata[tahun]['sub_kategori']['Undangan Rapat'][bulan]}`);
        $("#Masuk-statistikbulan").text(`${listdata[tahun]['sub_kategori']['Masuk Ruang Server'][bulan]}`);
        $("#Insiden-statistikbulan").text(`${listdata[tahun]['sub_kategori']['Insiden'][bulan]}`);
        console.log(tahun)
        console.log(bulan)

      }
      $('body').on('change', '#bulanpilih, #tahunpilih', function() {
        tahun = $('#tahunpilih').val()
        bulan = $('#bulanpilih').val()
        dashboard(tahun, bulan);
      });

      if (listdata != null) {
        dashboard('All', 'Januari');
      }
    });
  </script>
  <!-- statisik tahun -->
  <script>
    let listdatatahun = <?= json_encode($this->data['list_data']) ?>;
    //console.log(listdatatahun);
    $(document).ready(function() {
      function statistiktahun(tahun) {
        //bulan = 'Desember'
        //$("#datatahunpilihan").text(`${listdata['All']['tiket']['Desember']}`); 
        $("#Singa-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['Singa Rusia']}`);
        $("#Internet-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['Internet & Jaringan']}`);
        $("#Sistem-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['Sistem Operasi']}`);
        $("#Software-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['Software']}`);
        $("#Hardware-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['Hardware']}`);
        $("#Aplikasi-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['Aplikasi']}`);
        $("#Pengembangan-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['Pengembangan Jaringan']}`);
        $("#Lain-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['Lain-Lain']}`);
        $("#Teleconference-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['Teleconference']}`);
        $("#File-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['File Sharing dan Cloud']}`);
        $("#Undangan-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['Undangan Rapat']}`);
        $("#Masuk-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['Masuk Ruang Server']}`);
        $("#Insiden-statistiktahun").text(`${listdatatahun[tahun]['sub_kategori']['Insiden']}`);
      }
      $('body').on('change', '#tahunpilihtahun', function() {
        //alert($(this).val());
        statistiktahun($(this).val());
      });
      if (listdatatahun != null) {
        statistiktahun(<?= date("Y") ?>);
      }
    });
  </script>
  <!-- Rekap petugas tahun -->
  <script>
    let petugastahundata = <?= json_encode($this->data['list_data']) ?>;
    $(document).ready(function() {
      $(function() {
        $('#petugasrekap').DataTable({
          "paging": true,
          "lengthChange": true,
          "searching": true,
          "ordering": true,
          "info": true,
          "autoWidth": false,
          "responsive": true,
          // order: [
          //     [0, 'desc']
          // ],
          "buttons": ["copy", "csv", "excel", "pdf", "print"]
        }).buttons().container().appendTo('#petugas_wrapper .col-md-6:eq(0)');
      });

      function petugastahun(tahun) {
        $.each(petugastahundata[tahun]['pengguna'], function(index, value) {
          document.getElementById("tableBody");
          tableBody.innerHTML += '<tr><td class="text-center">' + value.nama + '</td><td class="text-center">' + value.rating + '</td><td class="text-center">' + value.jumlah_tiket + '</td><td class="text-center">' + value.jumlah_tiket_rating + '</td><td class="text-center">' + value.point + '</td></tr>';
        });
      }
      $('body').on('change', '#tahunpilihtahunpetugas', function() {
        //alert($(this).val());
        $("#tableBody").empty();
        petugastahun($(this).val());
      });
      if (petugastahundata != null) {
        petugastahun('All');
      }
    });
  </script>

</body>

</html>