<div class="container">

    <div class="row pt-5">
        <div class="col-lg-4 col-md-5 mb-4">
            <div class="card shadow" style="border-radius: 15px;">
                <div class="card-header py-3" style="background: rgb(255,255,255);border-top-left-radius: 15px;border-top-right-radius: 15px;">
                    <p class="text-primary m-0 fw-bold">Status</p>
                </div>
                <div class="card-body">
                    <form>
                        <div class="row">
                            <div class="col-4">
                                <div class=" pt-3 text-center">
                                    <div class="progress__container">
                                        <div class="progress__bar js-bar"></div>
                                        <div class="progress__circle js-circle active">
                                            <span class="progress__span"></span>
                                            <h3></h3>
                                        </div>
                                        <div class="progress__circle js-circle">
                                            <span class="progress__span"></span>
                                        </div>
                                        <div class="progress__circle js-circle">
                                            <span class="progress__span"></span>
                                        </div>
                                        <div class="progress__circle js-circle">
                                            <span class="progress__span"></span>
                                        </div>
                                        <div class="progress__circle js-circle">
                                            <span class="progress__span"></span>
                                        </div>
                                        <div class="progress__circle js-circle">
                                            <span class="progress__span"></span>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="col-8 pt-2 ">
                                <div class="row ket-prosses ">
                                    <div>
                                        <a class="text-decoration-none thp non-aktif" data-id="1" style="cursor:pointer;">
                                            <h5 class="fw-bold">Permohonan</h5>
                                        </a>
                                        <h6>tiket dalam antrian</h>
                                    </div>
                                </div>
                                <div class="row ket-prosses ">
                                    <div>
                                        <a class="text-decoration-none thp non-aktif" data-id="2" style="cursor:pointer;">
                                            <h5 class="fw-bold">Perencanaan</h5>
                                        </a>
                                        <h6>tiket dalam antrian</h>
                                    </div>
                                </div>
                                <div class="row ket-prosses ">
                                    <div>
                                        <a class="text-decoration-none thp non-aktif" data-id="3" style="cursor:pointer;">
                                            <h5 class="fw-bold">Perancangan</h5>
                                        </a>
                                        <h6>tiket dalam antrian</h>
                                    </div>
                                </div>
                                <div class="row ket-prosses ">
                                    <div>
                                        <a class="text-decoration-none thp non-aktif" data-id="4" style="cursor:pointer;">
                                            <h5 class="fw-bold">Implementasi</h5>
                                        </a>
                                        <h6>tiket dalam antrian</h>
                                    </div>
                                </div>
                                <div class="row ket-prosses">
                                    <div>
                                        <a class="text-decoration-none thp non-aktif" data-id="5" style="cursor:pointer;">
                                            <h5 class="fw-bold">Pengujian</h5>
                                        </a>
                                        <h6>Operator lokasi</h>
                                    </div>
                                </div>
                                <div class="row">
                                    <div>
                                        <a class="text-decoration-none thp non-aktif" data-id="6" style="cursor:pointer;">
                                            <h5 class="fw-bold">Serah Terima</h5>
                                        </a>
                                        <h6>selesai dikerjakan</h>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="mb-3"></div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-8 col-md-7 ">

            <div class="row thp-all">
                <div class="col-lg-12 col-xxl-12">
                    <div class="card shadow mb-3" style="border-radius: 15px;">
                        <div class="card-header py-3" style="background: rgb(255,255,255);border-top-left-radius: 15px;border-top-right-radius: 15px;border-width: 0px;">
                            <h3 class="text-primary fw-bold nama-tahap">Perencanaan</h3>
                        </div>
                        <div class="card-body" style="background: rgba(0,0,0,0.19);border-radius: 15px;">
                            <h4 class="small fw-bold">Progress<span class="float-end progressbar-label"></span></h4>
                            <div class="progressbar-container">
                                <div class="progressbar-bar "></div>
                            </div>
                            <form>
                                <div class="row ">
                                    <div class="col">
                                        <!-- daftar tahapan -->
                                        <div>
                                            <!-- panggil id subtahapan disini -->
                                            <div class="accordion">


                                                <div class="accordion-item mb-2">
                                                    <h2 class="accordion-header" id="headingOne">
                                                        <button class="accordion-button fw-bold semibold collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#id-sub-tahapan-1" aria-expanded="true" aria-controls="id-sub-tahapan-1">
                                                            <input class="all checkbox" type="checkbox" id="option" disabled />
                                                            <div class="row mx-2 ">
                                                                <h4 class="fw-bold">Tahapan Flowchart</h4>
                                                        </button>
                                                    </h2>

                                                    <div id="id-sub-tahapan-1" class="accordion-collapse collapse">
                                                        <div class="accordion-body">
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <!-- close sub tahapan   -->
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row thp-permohonan">
                <div class="col-lg-12 col-xxl-12">
                    <div class="card shadow mb-3" style="border-radius: 15px;">
                        <div class="card-body">
                            <div>
                                <p class="text-primary m-0 fw-bold" style="padding-bottom: 10px;">Keterangan :</p>
                            </div>
                            <div class="row">
                                <div class="col">
<!--                                    <div class="mb-3"><label class="form-label"><strong>Judul</strong><br /></label><input id="judul" class="form-control" type="text" style="border-radius: 10px;" value="--><?//= $this->result['judul'] ?><!--" disabled /></div>-->
                                    <div class="mb-3"><label class="form-label"><strong>Pelapor</strong><br /></label><input id="pelapor" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->result['nama_pelapor'] ?>" disabled /></div>
                                    <div class="mb-3"><label class="form-label"><strong>Bagian</strong><br /></label><input id="bagian" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->result['bagian'] ?>" disabled /></div>
                                    <div class="mb-3"><label class="form-label"><strong>Unit Kerja</strong><br /></label><input id="Unit Kerja" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->result['unit_kerja'] ?>" disabled /></div>
                                    <div class="mb-3"><label class="form-label"><strong>HP</strong><br /></label><input id="hp" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->result['hp'] ?>" disabled /></div>
                                    <div class="mb-3"><label class="form-label"><strong>Email</strong><br /></label><input id="email" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->result['email'] ?>" disabled /></div>
                                </div>
                                <div class="col">
                                    <div class="mb-3"><label class="form-label"><strong>Gedung</strong></label><input id="gedung" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->result['gedung'] ?>" disabled /></div>
                                    <div class="mb-3"><label class="form-label"><strong>Lantai</strong></label><input id="lantai" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->result['lantai'] ?>" disabled /></div>
                                    <div class="mb-3"><label class="form-label"><strong>Ruangan</strong></label><input id="ruangan" class="form-control" type="text" style="border-radius: 10px;" value="<?= $this->result['ruangan'] ?>" disabled /></div>
                                    <div class="mb-3"><label class="form-label"><strong>Keterangan</strong><br /></label><textarea id="keterangan" class="form-control" rows="5" name="signature" style="border-radius: 15px;" value="<?= $this->result['keterangan'] ?>" disabled><?= $this->result['keterangan'] ?></textarea></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card shadow mb-3" style="border-radius: 15px;">
                        <div class="card-body">
                            <p class="text-primary m-0 fw-bold" style="padding-bottom: 10px;">Harap Lengkapi dokumen di
                                bawah ini</p>
                            <form method="post" enctype="multipart/form-data" class="needs-validation" action="/tiket/upload-Dokumen" novalidate>
                                <div class="row">
                                    <input type="hidden" name="id" class="form-control" value="<?= $this->result['id'] ?>">
                                    <? if ($this->result['pesan_revisi'] != null) { ?>
                                        <div class="fw-bold text-warning mb-2">
                                            <? $jumlah = (count($this->result['dokumen_lampiran']) >= 2) ? 0 : 2-(count($this->result['dokumen_lampiran'])) ?>
                                            Keterangan Revisi (Maksimal Upload <?= $jumlah ?> dari 2 Dokumen) : <p class='text-danger'><?= $this->result['pesan_revisi'] ?></p>
                                        </div>
                                    <? } ?>
                                    <div class="col">
                                        <div class="mb-3">
                                            <label class="form-label" for="nota">
                                                <strong>Nota Dinas atau KAK/TOR</strong><br />
                                            </label>
                                            <? if ($this->result['dokumen_lampiran'][1] != null) { ?>
                                                <div class='mb-2 d-flex align-items-center'>
                                                    Dokumen :<a target="_blank" href="<?= "/storage/index/dokumen-lampiran/{$this->result['dokumen_lampiran'][1]['doc_name']}/ext/{$this->result['dokumen_lampiran'][1]['ext']}" ?>"><i class="fa-regular fa-file fs-4 ms-2"></i></a>
                                                    <? if ($this->result['pesan_revisi'] != null) { ?>
                                                        <a class="text-danger ms-2 fs-4" href='/tiket/delete-dokumen/id/<?= $this->result['id'] ?>/id_dokumen/<?= $this->result['dokumen_lampiran'][1]['id_dokumen'] ?>'><i class="fa-solid fa-delete-left"></i></a>
                                                    <? } ?>
                                                </div>
                                                <? if ($this->result['dokumen_lampiran'][2] != null) { ?>
                                                    <div class='mb-2'>
                                                        Dokumen :<a target="_blank" href="<?= "/storage/index/dokumen-lampiran/{$this->result['dokumen_lampiran'][2]['doc_name']}/ext/{$this->result['dokumen_lampiran'][2]['ext']}" ?>"><i class="fa-regular fa-file fs-4 ms-2"></i></a>
                                                        <? if ($this->result['pesan_revisi'] != null) { ?>
                                                            <a class="text-danger ms-2 fs-4" href='/tiket/delete-dokumen/id/<?= $this->result['id'] ?>/id_dokumen/<?= $this->result['dokumen_lampiran'][2]['id_dokumen'] ?>'><i class="fa-solid fa-delete-left"></i></a>
                                                        <? } ?>
                                                    </div>
                                            <? }
                                            } ?>

                                            <? if ($this->result['dokumen_lampiran'] == null || $this->result['pesan_revisi'] != null) {
                                                for ($i = 0; $i < (2 - count($this->result['dokumen_lampiran'])); $i++) {?>
                                                <div>
                                                    <input id="nota" class="form-control" type="file" name='dokumen[]' required />
                                                    <div class="invalid-feedback">Tolong lampirkan dokumen!</div>
                                                    <div class="valid-feedback">
                                                        Baik!
                                                    </div>
                                                </div>
                                                    <br>
                                            <? }
                                            } ?>
                                        </div>
                                    </div>
                                </div>
                                <? if ($this->result['dokumen_lampiran'] == null && $this->result['pesan_revisi'] == null) { ?>
                                    <div class="text-end mb-3"><button class="btn btn-primary btn-sm" type="submit">Upload</button>
                                    </div>
                                <? } ?>
                                <? if ($this->result['pesan_revisi'] != null) { ?>
                                    <div class="text-end mb-3"><button class="btn btn-danger btn-sm" type="submit">Revisi</button>
                                    </div>
                                <? } ?>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card shadow mb-3" style="border-radius: 15px;">
                <div class="card-body">
                    <div>
                        <p class="fs-4 text-center m-0 fw-bold" style="padding-bottom: 25px;">Petugas</p>
                        <div class="row">
                            <div class="col">
                                <?php if ($this->result["tim_programmer"]["list_programmer"] != null) { ?>
                                    <div class="swiper mySwiper">
                                        <div class="swiper-wrapper pb-3">
                                            <?php foreach ($this->result["tim_programmer"]["list_programmer"] as $i) : ?>

                                                <div class="swiper-slide">
                                                    <div class="card text-center">
                                                        <div class="card-body text-center"><img class="rounded-circle mb-3 fit-cover" width="70" height="70" src="<?= $i['profile'] ?>">
                                                            <h5 class="fw-bold text-primary card-title mb-0"><strong><?= $i["nama"] ?></strong></h5>
                                                            <p class="text-muted card-text mb-2"><?= $i["jabatan"] ?></p>
                                                        </div>
                                                    </div>
                                                </div>

                                            <?php endforeach ?>
                                        </div>
                                        <div class="swiper-pagination pt-5"></div>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/stela/js/jquery.min.js"></script>
<script src="/stela/js/swiper-bundle.min.js"></script>
<!-- ini untuk all carouser -->
<script>
    var swiper = new Swiper(".mySwiper", {
        slidesPerView: 1,
        spaceBetween: 10,
        loop: true,
        loopFillGroupWithBlank: true,
        pagination: {
            el: ".swiper-pagination",
            clickable: true,
        },
        breakpoints: {
            260: {
                slidesPerView: 1,
                spaceBetween: 20,
            },
            500: {
                slidesPerView: 2,
                spaceBetween: 40,
            },
            1024: {
                slidesPerView: 3,
                spaceBetween: 50,
            },
        },

    });

    let statuss = "<?= count($this->result['tahapan']) ?>";
    let kategori = "<?= $this->result['id_sub_kategori'] ?>";

    // ==============================================================

    let detail = <?= json_encode($this->result["detail"]) ?>;
    let id_simpanan = <?= count($this->result["tahapan"]) ?>;
    // console.log(detail);
    // console.log(id_simpanan);
</script>