<div class="container">
        <div class="row">
            <div class="col-lg-6 col-xl-5 col-xxl-4 offset-xxl-0">
                <div class="p-5" style="background: var(--bs-white);border-radius: 29px;">
                    <div class="text-center">
                        <h4 class="text-dark mb-4">Terima Kasih, Keluhanmu Akan Segera Kami Proses</h4>
                    </div>
                    <form class="justify-content-center align-items-center user">
                        <div class="mb-3"><input class="form-control form-control-user" type="text" id="exampleInputEmail"  placeholder="" name="" style="border-radius: 15px;background: var(--bs-card-cap-bg);"></div>
                        <button class="btn btn-primary d-block btn-user w-100" type="submit" style="border-radius: 15px;">Lacak Status</button>
                    </form>
                    <div class="text-center"></div>
                    <div class="text-center"></div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-5 col-xxl-5 offset-xl-1 offset-xxl-2 d-none d-lg-flex"><img src="stela/assets/animasilogin.png"></div>
        </div>
        <div class="card shadow-lg o-hidden border-0 my-5" style="background: rgba(255,255,255,0);">
            <div class="card-body p-0"></div>
        </div>
    </div>