<div class="card shadow" style="border-bottom-right-radius: 15px;border-top-right-radius: 15px;border-top-left-radius: 15px;border-bottom-left-radius: 15px;">
    <!-- <div class="card-header py-3">
            <p class="text-primary m-0 fw-bold">Daftar Petugas</p>
        </div> -->
    <div class="card-body">
        <div class="table-responsive table" id="" role="grid" aria-describedby="dataTable_info" style="background: var(--bs-table-bg);border-radius: 10px;">
            <table id="petugas" class="table table-striped">
                <thead style="background: rgba(208,204,204,0.76);">
                    <tr>
                        <th class="">Id Petugas</th>
                        <th>Nama</th>
                        <th class="text-center">Jumlah Tiket</th>
                        <th class="text-center">Jumlah Tiket Diberi Rating</th>
                        <th class="text-center">Rating</th>
                        <th class="text-center">Poin</th>
                        <th class="text-center">Tindakan</th>
                    </tr>
                </thead>
                <tbody style="background: rgba(231,231,231,0.64);">
                    <?php
                    if ($this->data == null) {
                        # code...
                    } else {
                        foreach ($this->data as $data) {
                            echo "<tr>";
                            echo "<td>" . $data['id'] . "</td>";
                            echo "<td>" . $data['nama'] . "</td>";
                            echo "<td align='center'>" . $data['jumlah_tiket'] . "</td>";
                            echo "<td align='center'>" . $data['jumlah_tiket_nilai'] . "</td>";
                            echo "<td align='center'>" . "<span class='stars' data-rating='{$data['rating']}' data-num-stars='5'></span>" . "<br/>" . "</td>";
                            echo "<td align='center'>" . round($data['jumlah_tiket_nilai'] * $data['rating'], 2) . "</td>";
                            echo "<td align='center'background: rgb(223,78,87);>";
                            echo "<a class='btn btn-secondary' type='button' style='margin: 13px;background: rgb(53,168,184);' href='/admin/detail-petugas/id/" . $data['id'] . "'>DETAIL</a></td>";
                            echo "</tr>";
                        }
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</div>